# Generated by Django 2.2.1 on 2019-05-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
